base_url = "https://carun.github.io"
title = "Arun Chandrasekaran"
description = "Arun's random stuff"
author = "Arun Chandrasekaran"
compile_sass = true
generate_feeds = true
feed_filenames = ["atom.xml"]

[markdown]
highlight_code = true
highlight_theme = "css"
bottom_footnotes = true

[slugify]
paths = "safe"
